### ISSUE TITLE
PB not achievable

### ISSUE THREAD

**Issue by nafck** [College-Kings/College-Kings#267]
![act](https://user-images.githubusercontent.com/108369429/197340425-e6067187-7d1a-4da7-84fb-0f62ea66865f.png)

Only I find it weird that in CK1, if I start the PB from the very beginning, I don't get any achievements? (Compared to part 1 from CK2's Episode 1 PB, I mean)

**Comment by Condy-jpg** [comment]
Closed as not in scope for CK1. If some achievements are locked behind a specific reputation and you can lock a reputation in the path builder then that should disqualify you from earning achievements.

When because of save transfer issues thr path builder is the only way forn some people to continue progress into CK2, achievements are allowed there.
